import { AnalysisSchema, type Evidence } from "../src/contracts.ts";
export const evidence: Evidence = {
  schemaVersion: "1.0",
  source: {
    url: "https://example.com/",
    finalUrl: "https://example.com/",
    capturedAt: "2026-09-13T00:00:00Z",
  },
  viewports: [
    {
      name: "desktop",
      width: 1440,
      height: 1000,
      pageHeight: 1000,
      elements: [
        {
          id: "desktop-0",
          selector: "h1",
          tag: "h1",
          role: "h1",
          text: "Editorial",
          geometry: { x: 30, y: 30, width: 600, height: 70 },
          styles: {
            "font-family": "Georgia",
            "font-size": "64px",
            "font-weight": "400",
            "line-height": "72px",
            "letter-spacing": "-1px",
            color: "rgb(30, 30, 30)",
            "background-color": "rgb(250, 250, 245)",
            "padding-top": "24px",
            "border-top-left-radius": "8px",
          },
        },
        {
          id: "desktop-1",
          selector: "p",
          tag: "p",
          role: "p",
          text: "Text",
          geometry: { x: 30, y: 120, width: 400, height: 30 },
          styles: {
            "font-family": "Arial",
            "font-size": "16px",
            "font-weight": "400",
            "line-height": "24px",
            "letter-spacing": "normal",
            color: "rgb(30, 30, 30)",
            "background-color": "rgba(0, 0, 0, 0)",
            "padding-top": "8px",
            "border-top-left-radius": "0px",
          },
        },
      ],
      variables: {},
      fonts: ["Georgia"],
      animations: [],
      warnings: [],
    },
  ],
  warnings: [],
};
export const analysis = AnalysisSchema.parse({
  name: "安静的编辑设计",
  summary: "用衬线标题和留白表达内容层次。",
  tags: ["Editorial"],
  philosophy: "将阅读内容放在首位。",
  colorStrategy: "克制的中性色形成对比。",
  typographyStrategy: "Georgia 衬线字体负责标题。",
  layoutStrategy: "内容从左侧顺序展开。",
  spacingStrategy: "采用浏览器提取的间距。",
  surfaceStrategy: "平面表面减少视觉噪声。",
  shapeStrategy: "少量圆角用于柔化容器。",
  componentStrategy: "标题和段落构成阅读结构。",
  motionStrategy: "没有观察到动态效果。",
  responsiveStrategy: "现有证据只有桌面视口，不能推断移动端。",
  signatureTraits: [1, 2, 3].map((i) => ({
    description: "以可观察的排版特征组织设计 " + i,
    evidenceIds: ["desktop-0"],
  })),
  do: ["使用实测字体声明。", "保持阅读层级清晰。", "保留大面积留白。"],
  dont: [
    "不要添加无依据的颜色。",
    "不要堆叠装饰性阴影。",
    "不要推断未知交互。",
  ],
});
